### ISSUE TITLE
[Improvement] Add support for `x-amz-acl`

### ISSUE THREAD

**Issue by jimmya** [anthonycastelli/s3-storage#2]
I'm really grateful for this package.
I was thinking about a way to add support for the access control header but I couldn't really come up with a way because of the current structure of the `storage-kit` package.

I would love to hear your thoughts about it, and would be willing to contribute!

**Comment by anthonycastelli** [comment]
So, the way things work in this case would be passing metadata to the put request. If you take a look at the method parameters, there is a coddle param that you can pass in info for. https://github.com/anthonycastelli/s3-storage/blob/master/Sources/S3Storage/S3Adapter.swift#L76

The problem I came across with that is that extracting the data becomes a bit tough, however, there might be a way to create a specific decoder using the reflection/mirror properties. I'll have to play around with it a bit. Feel free to submit PR's with ideas and such. 👍

**Comment by anthonycastelli** [comment]
This is now part of the latest release 👍
